#!/usr/bin/env python3
# vim: syntax=python ts=4 et sw=4 sts=4:

# Generates CSV files for use with graphviz.

import argparse
import sys

import liftdb
import logparse
from common import *

# Parse arguments.
parser = argparse.ArgumentParser()
parser.add_argument('lift')
parser.add_argument('period', help='take from specified time period',
                    choices=['daily', 'weekly'])
parser.add_argument('data', help='output this on the y-axis',
                    choices=['e1rm', 'volume', 'tonnage', 'fatigue', 'repranges'])
parser.add_argument('-i', '--include-related', help='include related lifts in calculations',
                    action="store_true")
args = parser.parse_args()


if args.data == "e1rm" and args.include_related:
    sys.exit(" Error: --include-related does not make sense with e1rm.")


#####################################################################


# Whether the lift matches the script arguments. Used for filtering.
def liftmatches(lift):
    if args.include_related and liftdb.related(args.lift, lift.name):
        return True
    return args.lift == lift.name


class WeeklyIterator:
    def __init__(self, sessions):
        self.sessions = sessions

    def __iter__(self):
        self.idx = 0
        return self

    # Whether the two given dates are in the same training week.
    # A training week is Sunday through Saturday (inclusive).
    def __sameweek(self, a, b):
        # Canonicalize each date according to the last Sunday.
        # isoweekday() gives 1 for Monday, 7 for Sunday.
        # So in terms of mapping how much to subtract:
        #  isoweekday -> subtract_amount
        #  [1,2,3,4,5,6,7] -> [1,2,3,4,5,6,0]
        subtract_amount_a = a.isoweekday() % 7
        subtract_amount_b = b.isoweekday() % 7

        week_a = a.toordinal() - subtract_amount_a
        week_b = b.toordinal() - subtract_amount_b

        return week_a == week_b

    def __next__(self):
        if self.idx >= len(self.sessions):
            raise StopIteration

        # Generate a list of sessions from here until Saturday (inclusive).
        # In terms of weekday(), Saturday is a return value of 6.
        startdate = self.sessions[self.idx].date
        acc = []

        for i in range(self.idx, len(self.sessions)):
            if self.__sameweek(startdate, self.sessions[i].date):
                acc.append(self.sessions[i])
            else:
                break

        self.idx += len(acc)
        return acc


def lift_e1rm_daily():
    arr = []
    for session in sessions:
        e1rm = session.e1rm(liftmatches)
        if e1rm > 0:
            arr.append([session.date, e1rm])
    return arr


# Max E1RM over the entire week (Sun-Sat).
def lift_e1rm_weekly():
    arr = []
    for week in WeeklyIterator(sessions):
        e1rm = max([0] + list(map(lambda x: x.e1rm(liftmatches), week)))
        if e1rm > 0:
            date = week[-1].date # Use the end date.
            arr.append([date, e1rm])
    return arr
        

def lift_volume_daily():
    arr = []
    for session in sessions:
        volume = session.volume(liftmatches)
        if volume > 0:
            arr.append([session.date, volume])
    return arr 


def lift_volume_weekly():
    arr = []
    for week in WeeklyIterator(sessions):
        volume = sum(s.volume(liftmatches) for s in week)
        if volume > 0:
            date = week[-1].date # Use the end date.
            arr.append([date, volume])
    return arr


def lift_tonnage_daily():
    arr = []
    for session in sessions:
        tonnage = session.tonnage(liftmatches)
        if tonnage > 0:
            arr.append([session.date, tonnage])
    return arr 


def lift_tonnage_weekly():
    arr = []
    for week in WeeklyIterator(sessions):
        tonnage = sum(s.tonnage(liftmatches) for s in week)
        if tonnage > 0:
            date = week[-1].date # Use the end date.
            arr.append([date, tonnage ])
    return arr


def lift_repranges_daily():
    arr = []
    for session in sessions:
        ranges = [0,0,0,0] # 1, 2-3, 4-6, 7+
        for lift in filter(liftmatches, session.lifts):
            for set in lift.get_worksets():
                if set.reps == 0:
                    continue
                if set.reps == 1:
                    ranges[0] += 1
                elif set.reps <= 3:
                    ranges[1] += 1
                elif set.reps <= 6:
                    ranges[2] += 1
                else:
                    ranges[3] += 1
        if sum(ranges) > 0:
            arr.append([session.date, ranges])
    return arr


def lift_repranges_weekly():
    arr = []
    for week in WeeklyIterator(sessions):
        ranges = [0,0,0,0] # 1, 2-3, 4-6, 7+
        for session in week:
            for lift in filter(liftmatches, session.lifts):
                for set in lift.get_worksets():
                    if set.reps == 0:
                        continue
                    if set.reps == 1:
                        ranges[0] += 1
                    elif set.reps <= 3:
                        ranges[1] += 1
                    elif set.reps <= 6:
                        ranges[2] += 1
                    else:
                        ranges[3] += 1
        if sum(ranges) > 0:
            arr.append([session.date, ranges])
    return arr


def lift_fatigue_daily():
    arr = []
    for session in sessions:
        fatigue = 0

        # Fatigue is directly cumulative between lifts in a session.
        for lift in filter(liftmatches, session.lifts):
            fatigue += lift.fatigue()

        if fatigue > 0:
            arr.append([session.date, fatigue])
    return arr


def lift_fatigue_weekly():
    arr = []
    for week in WeeklyIterator(sessions):
        fatigue = 0
        for session in week:
            # This metric is a little arbitrary: total recovery needed.
            for lift in filter(liftmatches, session.lifts):
                fatigue += lift.fatigue()

        if fatigue > 0:
            date = week[-1].date # Use the end date.
            arr.append([date, fatigue])
    return arr


#####################################################################


def print_csv(csvarr):
    for row in csvarr:
        print(', '.join(map(str, row)).replace('[','').replace(']',''))


#####################################################################


sessions = logparse.parse('exlog')

if args.period == "daily" and args.data == "e1rm":
    print_csv(lift_e1rm_daily())

elif args.period == "daily" and args.data == "volume":
    print_csv(lift_volume_daily())

elif args.period == "daily" and args.data == "tonnage":
    print_csv(lift_tonnage_daily())

elif args.period == "daily" and args.data == "repranges":
    print_csv(lift_repranges_daily())

elif args.period == "daily" and args.data == "fatigue":
    print_csv(lift_fatigue_daily())

elif args.period == "weekly" and args.data == "e1rm":
    print_csv(lift_e1rm_weekly())

elif args.period == "weekly" and args.data == "volume":
    print_csv(lift_volume_weekly())

elif args.period == "weekly" and args.data == "tonnage":
    print_csv(lift_tonnage_weekly())

elif args.period == "weekly" and args.data == "repranges":
    print_csv(lift_repranges_weekly())

elif args.period == "weekly" and args.data == "fatigue":
    print_csv(lift_fatigue_weekly())
